### ISSUE TITLE
[FEATURE] todo ajax

### ISSUE THREAD

**Issue by hwanheejung** [TaskStock/TaskStock#106]
## 📃 상세 내용
- 상세 내용 작성..
## ✔️ 체크리스트
- [ ] search css
- [ ] settings css
- [ ] following follower layout 
- [ ] 캘린더 대신 잔디그래프?
- [ ] todo check ajax
- [ ] todo ajax paint
- [ ] candlestick chart 위에 layout 구성
